version: '2'
volumes:
  artifactory:
    external: true
    driver: rancher-ebs
services:
  artifactory-pro:
    image: docker.bintray.io/jfrog/artifactory-pro:latest
    stdin_open: true
    tty: true
    volumes_from:
    - vartifactory
    ports:
    - 8081:8081/tcp
    labels:
      io.rancher.sidekicks: vartifactory
  vartifactory:
    image: busybox
    stdin_open: true
    volumes:
    - artifactory:/var/opt/jfrog/artifactory
    volume_driver: ${VOLUME_DRIVER}
    tty: true
