version: '2'
catalog:
  name: Artifactory Pro
  version: 5.4.6
  description: |
    STCL-Tech Artifactory Pro (Experimental)
  maintainer: "Rich Bos <richard.bosomworth@skeltonthatcher.com>"
  uuid: artifactory-pro-0
  questions:
    - variable: "VOLUME_DRIVER"
      description: "The volume driver to use"
      label: "Volume Driver"
      required: true
      default: "local"
      type: enum
      options:
        - local
        - rancher-nfs
        - rancher-efs
        - rancher-ebs
services:
  artifactory-pro:
    scale: 1
    start_on_create: true
  vartifactory:
    scale: 1
    start_on_create: true
