version: '2'
gocdio-server:
  labels:
    gocd.role: server
  tty: true
  image: gocd/gocd-server:v17.3.0
  volumes:
  - ${data_volume}:/godata
  volume_driver: ${volume_driver}
  environment:
  - SERVER_MEM=${mem_initial}m
  - SERVER_MAX_MEM=${mem_max}m
  - GO_SERVER_SYSTEM_PROPERTIES=${jvm_options}
  ports:
  - ${public_port}:8153
  - ${ssh_port}:8154
  labels:
    io.rancher.container.hostname_override: container_name
