.catalog:
  name: gocdio-server
  version: 17.3.0-rancher1
  description: |
    STCL GoCD Server
  maintainer: "Rich Bos <richard.bosomworth@skeltonthatcher.com"
  tested_rancher_version: v1.5.3
  uuid: goserver-0
  questions:
    - variable: public_port
      description: "Public port to access the gocd server"
      label: "Public Port"
      required: true
      default: "8153"
      type: "int"
    - variable: ssh_port
      description: "Port for go-agent access"
      label: "Agent Port"
      required: true
      default: "8154"
      type: "int"
    - variable: "data_volume"
      description: "Volume to save goserver data"
      label: "Data volume:"
      required: true
      default: "ebs"
      type: "string"
    - variable: "volume_driver"
      description: "The volume driver type"
      label: "Volume driver:"
      default: "rancher-ebs"
      required: true
      type: "string"
gocdio-server:
  scale: 1
  retain_ip: true
  health_check:
    port: 8153
    interval: 5000
    unhealthy_threshold: 5
    request_line: GET /go/agents HTTP/1.0
    healthy_threshold: 2
    response_timeout: 5000
