version: '2'
catalog:
  name: gocdio-agent
  version: 17.3.0-rancher
  description: |
    STCL GoCD Agent
  maintainer: "Richard Bosomworth <richard.bosomworth@skeltonthatcher.com"
  tested_rancher_version: v1.5.3
  uuid: goagent-0
  questions:
    - variable: "jvm_options"
      description: "JVM options for memory, heap etc"
      label: "JVM Options"
      required: true
      default: -Xms512m -Xmx1024m
      type: "string"
    - variable: "goserver_ip"
      description: |
        Choose the GoCD service to connect.
      label: "GoCD server stack/service"
      default: "gocdio-server/gocdio-server"
      required: true
      type: "service"
    - variable: "goserver_port"
      description: "GoCD server port"
      label: "GoCD server port:"
      required: true
      default: 8153
      type: "int"
    - variable: "scale"
      description: "GoCD agent instances"
      label: "Instances:"
      required: true
      default: 1
      type: "int"
    - variable: "reg_key"
      description: "Auto register"
      label: "Agent registration key"
      required: true
      default: 1234567890-0987654321-1234567890
      type: "string"
gocdio-agent:
  scale: ${scale}
  retain_ip: true
