splunk:
  image: splunk/splunk:6.5.3-monitor
  environment:
    SPLUNK_START_ARGS: --accept-license --answer-yes
    SPLUNK_ENABLE_LISTEN: 9997
    SPLUNK_ADD: tcp 1514
    SPLUNK_USER: root
  volumes:
    - ${data_volume}:/opt/splunk
    - /var/lib/docker/containers:/host/containers:ro
    - /var/run/docker.sock:/var/run/docker.sock:ro
  volume_driver: ${volume_driver}
  ports:
    - ${public_port}:8000
    - 9997:9997
    - 8088:8088
    - 1514:1514
  health_check:
    # Which port to perform the check against
    port: 8000
    # Interval is measured in milliseconds
    interval: 2000
    initializing_timeout: 60000
    unhealthy_threshold: 3
    # Strategy for what to do when unhealthy
      # In this service, Rancher will recreate any unhealthy containers
    strategy: recreate
    healthy_threshold: 2
    # Response timeout is measured in milliseconds
    response_timeout: 2000
