.catalog:
  name: splunk-ent-mon
  version: 6.5.3-monitor
  description: |
    STCL-Tech Splunk Enterprise M
  maintainer: "Rich Bos <richard.bosomworth@skeltonthatcher.com"
  uuid: splunk-ent-mon-0
  questions:
    - variable: public_port
      description: "Public port to access splunk"
      label: "Public Port"
      required: true
      default: "8000"
      type: "int"
    - variable: "data_volume"
      description: "EBS volume for splunk data"
      label: "Data volume:"
      required: true
      default: "splunkebs"
      type: "string"
    - variable: "volume_driver"
      description: "The volume driver type"
      label: "Volume driver:"
      default: "rancher-ebs"
      required: true
      type: "string"
splunk-ent-mon:
  scale: 1
  retain_ip: true
  health_check:
    # Which port to perform the check against
    port: 8000
    # Interval is measured in milliseconds
    interval: 2000
    initializing_timeout: 60000
    unhealthy_threshold: 3
    # Strategy for what to do when unhealthy
    # In this service, Rancher will recreate any unhealthy containers
    strategy: recreate
    healthy_threshold: 2
    # Response timeout is measured in milliseconds
    response_timeout: 2000
