name: gocd-server
description: |
  (Experimental) STCL GoCD server
version: 17.3-rancher1
category: Continuous Integration
maintainer: "Rich Bos <richard.bosomworth@skeltonthatcher.com>"
tested_rancher_version: v0.59.0
license:
