name: gocdio-agent
description: |
  STCL GoCD agent1
version: 17.3.0-rancher
category: Continuous Integration
maintainer: "Rich Bos <richard.bosomworth@skeltonthatcher.com"
tested_rancher_version: v1.5.3
license:
